# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Change working directory to project root
        run: cd ${{ github.workspace }}

      - name: Change working directory to Flutter project
        run: cd test_ci_cd/test_ci_cd

      - name: List files in current directory
        run: ls

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '18'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.7'

      

      - name: Clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build iOS IPA
        run: flutter build ios --release --no-codesign
