# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '18'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.7'

      - name: Clean
        run: |
          cd ${{ github.workspace }}
          cd test_ci_cd
          flutter clean

      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          cd test_ci_cd
          flutter pub get

      # - name: Build Android APK
      #   run: |
      #     cd ${{ github.workspace }}
      #     cd test_ci_cd
      #     flutter build apk --release

      - name: Build iOS IPA
        run: |
          cd ${{ github.workspace }}
          cd test_ci_cd
          flutter build ipa --release --no-codesign
