# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '18'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.1'

      - name: Clean
        run: |
          cd ${{ github.workspace }}
          cd test_ci_cd
          flutter clean

      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          cd test_ci_cd
          flutter pub get


      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
            fileName: test_android_keystore.jks
            encodedString: ${{ secrets.KEYSTORE_BASE64 }}
        env:
            ANDROID_KEYSTORE_FILEPATH: ${{ steps.android_keystore.outputs.filePath }}
      - name: Create key.properties
        run: |
          cd ${{ github.workspace }}
          cd test_ci_cd
          echo "storeFile=${{ env.ANDROID_KEYSTORE_FILEPATH }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Build Android APK
        run: |
          cd ${{ github.workspace }}
          cd test_ci_cd
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Project
          path: test_ci_cd/build/app/outputs/flutter-apk/app-release.apk

      # - name: Download APK Artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: My-App
      #     path: path/to/download/directory
      # - name: Build iOS IPA
      #   run: |
      #     cd ${{ github.workspace }}
      #     cd test_ci_cd
      #     flutter build ipa --release --no-codesign
